version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8002:80"
    depends_on:
      - backend
    networks:
      - book-inventory-network

  backend:
    build: ./backend
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bookdb
    depends_on:
      - mongodb
    networks:
      - book-inventory-network

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - book-inventory-network

  database-init:
    build: ./database
    depends_on:
      - mongodb
    networks:
      - book-inventory-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - book-inventory-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - book-inventory-network

volumes:
  mongo-data:

networks:
  book-inventory-network:
    driver: bridge
